global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'questboard'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:5000']
        labels:
          service: 'questboard'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
